server:
  port: 8087

spring:
  application:
    name: demo-consumer
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/rain?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: rain1234
  cloud:
    nacos:
      discovery:
        ###nacos注册地址
        server-addr: 192.168.15.152:8850
#        namespace: local
        username: nacos
        password: nacos
      config:
        server-addr: 192.168.15.152:8850
        file-extension: yaml
#      discovery:
#        server-addr: localhost:8850
#        username: nacos
#        password: nacos
