server:
  port: 8809

spring:
  application:
    name: demo-sentinel
  cloud:
    sentinel:
      transport:
        # ??sentinel??????
        dashboard: 127.0.0.1:8080
        # ?????Sentinel???????????????????????HttpServer
        port: 8719

#??actuator??
management:
  endpoints:
    web:
      exposure:
        include: '*'
